### PR TITLE
Revert "Update Jackson to remove deserialisation vulnerability"

### PR DESCRIPTION
**Pull request by Antonio-Pleo**
Reverts pleo-io/prop#3

### CODE REVIEW

**Comment by Antonio-Pleo** [comment]
@GuiSim failing because of "Rule "RepositoryWritePolicy" failures" your help needed.

**Comment by GuiSim** [comment]
Why are we reverting this?

**Comment by Antonio-Pleo** [comment]
when I merged into master, the build failed!

**Comment by GuiSim** [comment]
You can't deploy a non-SNAPSHOT version more than once in Maven-land.
You can't just rollback the version number.

**Comment by GuiSim** [comment]
What's the status on this @Antonio-Pleo ?

**Comment by Antonio-Pleo** [comment]
Ok so I don´t need to revert it..

**Comment by GuiSim** [comment]
@Antonio-Pleo maybe you do, I do not know what the problem is.
What I know is that you can't go _backwards_ with deployed version. If you're rolling back changes, you need to deploy a higher version number with the changes rolled back. Makes sense?

**Pull request closed without merging**
